(()=>{
 const panel=document.querySelector('.type-panel');if(!panel)return;
 const STORE='chen-yue-text-edits-v1';let edits={};try{edits=JSON.parse(localStorage.getItem(STORE))||{}}catch{}
 const page=location.pathname,parts=el=>[...el.childNodes].filter(n=>n.nodeType===3),values=el=>parts(el).map(n=>n.nodeValue);
 const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
 for(const [selector,edit] of Object.entries(edits[page]||{})){try{const el=document.querySelector(selector);if(el&&Array.isArray(edit.original)&&Array.isArray(edit.replacement)&&equal(values(el),edit.original))parts(el).forEach((n,i)=>n.nodeValue=edit.replacement[i]??n.nodeValue)}catch{}}
 const section=document.createElement('section');section.className='gpt-editor';section.innerHTML=`<h3>GPT 文字润色</h3><details class="gpt-connection"><summary>连接 GPT</summary><p class="type-help">使用 OpenAI API，按 API 用量计费。密钥只保留在本地服务器内存，重启后需重新填写。</p><label for="gpt-key">OpenAI API Key</label><input id="gpt-key" type="password" autocomplete="off" placeholder="sk-…"><div class="type-actions"><button type="button" data-connect>连接</button><button type="button" data-disconnect>断开</button><a href="https://platform.openai.com/api-keys" target="_blank" rel="noopener noreferrer">获取 API Key ↗</a></div><p class="type-help" data-connection-status>正在检查连接…</p></details><p class="type-help">先点选页面文字。生成时只发送下方原文和修改要求；建议需确认后才会替换。</p><label for="gpt-original">选中的原文</label><textarea id="gpt-original" rows="3" readonly placeholder="请先点选页面文字"></textarea><label for="gpt-instruction">希望怎么修改</label><textarea id="gpt-instruction" rows="2" maxlength="1000" placeholder="例如：更精简，突出我的贡献，保持真实自然"></textarea><div class="type-actions"><button type="button" data-preset="润色文字，表达清晰自然，适合求职作品集。">润色</button><button type="button" data-preset="精简文字，删除重复和空话，保留关键事实和全部数据。">精简</button><button type="button" data-preset="调整为专业、克制的语气，清晰表达我的实际工作与贡献，不夸大。">更专业</button></div><div class="type-actions"><button type="button" data-generate disabled>生成建议</button><button type="button" data-cancel hidden>取消生成</button></div><label for="gpt-draft">建议文字（可继续编辑）</label><textarea id="gpt-draft" rows="4" maxlength="10000" placeholder="GPT 的建议会显示在这里"></textarea><div class="type-actions"><button type="button" data-apply disabled>替换选中文字</button><button type="button" data-undo disabled>恢复原文</button></div><p class="type-help" data-gpt-status role="status">文字修改保存在当前浏览器。</p>`;
 panel.querySelector('[data-status]').before(section);document.querySelector('.type-launch').textContent='Aa 文字编辑';panel.querySelector('h2').textContent='文字与字体';
 let selected=null,draftFor=null,controller=null,version=0,configured=false;
 const original=section.querySelector('#gpt-original'),draft=section.querySelector('#gpt-draft'),instruction=section.querySelector('#gpt-instruction'),message=section.querySelector('[data-gpt-status]'),connection=section.querySelector('[data-connection-status]');
 const button=key=>section.querySelector('[data-'+key+']');
 const sync=()=>{button('generate').disabled=!selected||!configured||!!controller;button('cancel').hidden=!controller;button('apply').disabled=!selected||draftFor!==selected||!draft.value.trim()||!!controller;button('undo').disabled=!selected||!edits[page]?.[selected.key]};
 const request=async(route,data,signal)=>{const response=await fetch('/api/gpt/'+route,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Portfolio-Editor':'1'}:{},body:data?JSON.stringify(data):undefined,signal});let result;try{result=await response.json()}catch{throw new Error('请使用已启动的本地服务器打开网页。')}if(!response.ok)throw new Error(result.error||'请求失败');return result};
 const check=()=>request('status').then(result=>{configured=result.configured;connection.textContent=configured?'API Key 已配置，生成时验证可用性。':'尚未连接，请填写 API Key。';sync()}).catch(error=>{connection.textContent=error.message});check();
 button('connect').addEventListener('click',async()=>{const input=section.querySelector('#gpt-key');button('connect').disabled=true;try{const result=await request('connect',{key:input.value});configured=result.configured;input.value='';connection.textContent='已配置，仅在本地服务器内存保留。';sync()}catch(error){connection.textContent=error.message}finally{button('connect').disabled=false}});
 button('disconnect').addEventListener('click',async()=>{try{controller?.abort();await request('disconnect',{});configured=false;connection.textContent='已断开，密钥已从服务器内存清除。';sync()}catch(error){connection.textContent=error.message}});
 document.addEventListener('portfolio-text-selection',event=>{const next=event.detail;if(next?.element===selected?.element)return;controller?.abort();controller=null;version++;selected=next?.element?next:null;draftFor=null;draft.value='';original.value=selected?values(selected.element).filter(v=>v.trim()).join('\n').trim():'';sync()});
 section.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>instruction.value=b.dataset.preset));
 button('generate').addEventListener('click',async()=>{if(!selected)return;const current=selected,run=++version;controller=new AbortController();draftFor=null;sync();message.textContent='GPT 正在整理文字…';try{const result=await request('rewrite',{text:original.value,instruction:instruction.value||'润色文字，表达清晰自然，适合求职作品集。'},controller.signal);if(run!==version||selected!==current)return;draft.value=result.text;draftFor=current;message.textContent='建议已生成。确认内容后再点击替换。'}catch(error){if(run===version)message.textContent=error.name==='AbortError'?'已取消生成。':error.message}finally{if(run===version){controller=null;sync()}}});
 button('cancel').addEventListener('click',()=>controller?.abort());draft.addEventListener('input',sync);
 const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(edits));return true}catch{message.textContent='已替换，但浏览器无法保存；刷新后可能恢复。';return false}};
 button('apply').addEventListener('click',()=>{if(!selected||draftFor!==selected||!draft.value.trim())return;const nodes=parts(selected.element),before=values(selected.element),index=nodes.findIndex(n=>n.nodeValue.trim());if(index<0)return;const after=before.map((value,i)=>i===index?draft.value.trim():value.trim()?'':value);edits[page]??={};edits[page][selected.key]={original:edits[page][selected.key]?.original||before,replacement:after};nodes.forEach((node,i)=>node.nodeValue=after[i]);original.value=draft.value.trim();draftFor=null;if(save())message.textContent='已替换这一处文字，并保存在当前浏览器。';sync()});
 button('undo').addEventListener('click',()=>{const edit=selected&&edits[page]?.[selected.key];if(!edit)return;parts(selected.element).forEach((node,i)=>node.nodeValue=edit.original[i]??node.nodeValue);delete edits[page][selected.key];original.value=values(selected.element).filter(v=>v.trim()).join('\n').trim();draft.value='';draftFor=null;if(save())message.textContent='这一处已恢复原文。';sync()});
})();
