module.exports=function renderMazoo(p,{shell,esc}){
 const base='../../';
 const pic=(file,caption,cls='',eager=false)=>`<figure class="mz-picture ${cls}"><img class="${file.includes("fullbody")?"image-character":file.includes("s24_1")?"image-small":file.includes("product-")?"image-standard":file.includes("s24_2")||file.includes("s24_3")?"image-small":"image-feature"}" src="${base}assets/${file}" alt="${esc(caption)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async"><figcaption>${esc(caption)}</figcaption></figure>`;
 const socialPic=(file,caption)=>pic(file,caption,'mz-social-picture').replace('<img','<div class="mz-social-frame"><img').replace('<figcaption>','</div><figcaption>');
 const heading=(n,en,title,copy)=>`<header class="mz-heading"><p class="mz-eyebrow">${n} / ${en}</p><h2>${title}</h2><p class="mz-description">${copy}</p></header>`;
 const tags=['Brand Strategy','IP Design','Content Operation','Cultural Product','Social Media'];
 const nav=['BACKGROUND','POSITIONING','IP DESIGN','CONTENT SYSTEM','PRODUCT','SOCIAL MEDIA','OFFLINE','RESULT'];
 const body=`<article class="mazoo-case mazoo-rebrand">
<section class="mz-hero" id="mazoo-top"><div class="mz-wrap mazoo-container"><a class="return-home mz-back" href="../../index.html#intro">← 返回首页</a><div class="mz-hero-grid"><div><p class="mz-eyebrow">CASE 02 / MAZOO</p><h1>从传统文化<br>到年轻品牌</h1><p class="mz-english">From Cultural Heritage to a Youth Brand</p><p class="mz-subtitle">MAZOO 海缘妈祖品牌 IP 0→1</p><p class="mz-intro">以文化研究定义品牌，让 IP 成为连接产品、内容与渠道的共同语言，走进年轻人的日常生活。</p><div class="mz-tags">${tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="mz-hero-art"><span class="mz-brand-word" aria-hidden="true">MAZOO</span>${pic('mazoo/mazoo-fullbody.png','MAZOO 海缘妈祖原创品牌 IP','mz-main-ip',true)}</div><div class="mz-brand-chain"><span>BRAND TO EVERYDAY</span><strong>品牌 <i>→</i> 产品 <i>→</i> 内容 <i>→</i> 渠道</strong></div></div></div></section>
<nav class="mz-section-nav" aria-label="MAZOO 章节导航"><div class="mz-wrap mazoo-container">${nav.map((t,i)=>`<a href="#mz-${i+1}"><b>0${i>=5?i+2:i+1}</b> ${t}</a>${i===4?'<a href="#mz-pitch"><b>06</b> PITCH DECK</a>':''}`).join('')}</div></nav>
<section class="mz-section mz-background" id="mz-1"><div class="mz-wrap mazoo-container">${heading('01','BACKGROUND','如何让传统妈祖文化<br>进入年轻人的日常生活？','妈祖文化具有鲜明的传统属性，但与年轻人的日常表达存在距离。项目以日常情境作为连接点，让文化从“被认识”走向“被使用、被分享”。')}<div class="mz-context"><div><span>文化来源</span><h3>从传统符号出发</h3><p>保留冠冕、服饰与核心色彩，让年轻化表达仍有清晰的文化来源。</p></div><div><span>生活连接</span><h3>让角色进入日常</h3><p>从工作、休闲、出行与观影等情境切入，让 IP 与年轻用户建立关系。</p></div><div><span>品牌延展</span><h3>从角色走向品牌</h3><p>让统一的视觉与内容语言延伸到文创、社媒与线下场景。</p></div></div><ol class="mz-journey" aria-label="项目路径"><li>文化研究</li><li>品牌定位</li><li>IP形象</li><li>内容</li><li>产品</li><li>传播</li><li>用户反馈</li></ol></div></section>
<section class="mz-section mz-position" id="mz-2"><div class="mz-wrap mazoo-container">${heading('02','POSITIONING','传统文化 × 现代审美','将妈祖文化中的核心符号，以更年轻、更日常的视觉语言重新表达，建立一个既有文化来源、也能进入当代生活的品牌形象。')}<div class="mz-values"><article><span>01</span><h3>亲和</h3><p>通过圆润角色、柔和表情和简化造型，让妈祖形象更易被年轻用户接受。</p></article><article><span>02</span><h3>年轻</h3><p>以明快配色、生活化主题和轻松表达，让传统文化进入年轻人的内容语境。</p></article><article><span>03</span><h3>陪伴</h3><p>让角色不仅被观看，也出现在工作、休闲、出行和文创产品中。</p></article></div><p class="mz-position-note">品牌定义角色，内容建立关系，产品让文化进入日常。</p></div></section>
<section class="mz-section mz-design" id="mz-3"><div class="mz-wrap mazoo-container">${heading('03','IP DESIGN','保留文化辨识度，<br>简化视觉表达。','把传统元素转化为能在插画、产品与社交内容中持续延展的品牌资产。')}<div class="mz-design-grid"><div class="mz-design-notes"><article><span>01 / FACE</span><h3>人物五官</h3><p>以圆润轮廓与温和眉眼，建立亲和、可接近的角色性格。</p></article><article><span>02 / CROWN</span><h3>冠冕</h3><p>保留标志性的冠冕轮廓，将繁复装饰归纳为清晰的形状与色块。</p></article></div>${pic('mazoo/mazoo-fullbody.png','MAZOO 完整形象：冠冕、红衣与圆润五官','mz-design-ip')}<div class="mz-design-notes"><article><span>03 / COSTUME</span><h3>服饰</h3><p>延续红衣等传统视觉线索，简化衣纹细节，适应不同场景与载体。</p></article><article><span>04 / COLOR</span><h3>色彩</h3><p>以红、黄、蓝等鲜明色彩组合，建立统一而有活力的品牌识别。</p><div class="mz-swatches" aria-label="红、黄、蓝、绿、粉品牌配色"><i></i><i></i><i></i><i></i><i></i></div></article></div></div><div class="mz-symbol-strip">${['symbol-duck.png','symbol-fish.png','symbol-shell.png','symbol-pear.png','symbol-boat.png','symbol-flower.png'].map(f=>`<img class="image-icon" src="${base}assets/mazoo/${f}" alt="MAZOO 延展装饰符号" loading="lazy">`).join('')}<p>从主形象到延展符号<br><b>让品牌拥有一套可组合的视觉语言</b></p></div></div></section>
<section class="mz-section mz-content" id="mz-4"><div class="mz-wrap mazoo-container">${heading('04','CONTENT SYSTEM','随行妈祖，<br>陪伴每一种日常。','通过日常情境建立 IP 与年轻用户之间的关系，让角色拥有持续更新的内容主题。')}<div class="mz-life-grid">${[['s20_1','摸鱼妈祖','RELAX','在忙碌间隙，留一点自己的时间。'],['s20_2','工作妈祖','WORK','把陪伴感放进每一个工作日。'],['s20_3','飞行妈祖','TRAVEL','带着熟悉的文化符号出发。'],['s20_4','观影妈祖','MOVIE','一起进入故事，也一起享受休闲。']].map(([f,t,en,c])=>`<article>${pic('2026/'+f+'.jpg',t)}<div><span>${en}</span><h3>${t}</h3><p>${c}</p></div></article>`).join('')}</div></div></section>
<section class="mz-section mz-product" id="mz-5"><div class="mz-wrap mazoo-container">${heading('05','PRODUCT','从品牌形象，<br>到可以带走的日常。','将 IP 转化为明信片、贴纸、装饰品、钥匙扣、文具与其他文创，让品牌进入携带、使用和赠送的场景。')}<div class="mz-product-grid">${[['product-postcards.jpg','01 / PAPER','明信片','以纸品承载角色与祝福，连接记录和赠送。'],['product-stickers-stamps.jpg','02 / STATIONERY','贴纸与文具','让视觉符号融入手帐、装饰与日常表达。'],['product-keychains.jpg','03 / ACCESSORIES','钥匙扣与挂件','将角色变成随身携带的品牌触点。'],['product-phone-stands.jpg','04 / OBJECTS','装饰品与其他文创','延伸至手机支架等物件，连接功能与审美。']].map(([f,k,t,c])=>`<article>${pic('mazoo/'+f,'MAZOO '+t+'产品样机')}<span>${k}</span><h3>${t}</h3><p>${c}</p></article>`).join('')}</div></div></section>
<section class="mz-section mz-pitch" id="mz-pitch"><div class="mz-wrap mazoo-container">${heading('06','PITCH DECK','让品牌方案，<br>成为清晰的路演表达。','围绕竞赛路演，将文化理念、市场分析与用户洞察组织为演示内容，以统一的品牌视觉与开场动画呈现 MAZOO 的项目思路。')}<div class="mz-pitch-opening"><figure class="mz-pitch-video"><video controls autoplay loop muted playsinline preload="auto" poster="../../assets/mazoo/pitch-opening-poster.jpg" aria-label="MAZOO 竞赛路演 PPT 开场动画"><source src="../../assets/mazoo/pitch-opening.mp4" type="video/mp4">当前浏览器无法播放视频，<a href="../../assets/mazoo/pitch-opening.mp4">查看开场动画</a>。</video><figcaption>MAZOO · 海缘妈祖，潮传共创 / 路演开场动画</figcaption></figure><div class="mz-pitch-intro"><span class="mz-eyebrow">OPENING FILM</span><h3>从开场，建立品牌印象。</h3><p>以品牌角色、色彩与延展符号构成开场动画，将路演带入 MAZOO 的视觉语境，再展开文化、产品与市场的叙事。</p></div></div><div class="mz-pitch-decks">${[['01','项目概述与文化理念','封面、目录与项目概述，建立路演的叙事框架。'],['02','文化背景与市场分析','从文化背景、市场问题与产品优势，说明项目的切入点。'],['03','用户洞察与竞争分析','围绕用户画像、消费偏好与品牌对比，呈现定位依据。']].map(([n,title,copy],i)=>`<article class="mz-pitch-deck"><div class="mz-pitch-copy"><span>${n} / PRESENTATION</span><h3>${title}</h3><p>${copy}</p></div><figure><button class="mz-deck-zoom" data-image="../../assets/mazoo/pitch-deck-${i+1}.jpg" data-caption="MAZOO 竞赛路演 · ${title}" aria-label="放大阅读：${title}"><img src="../../assets/mazoo/pitch-deck-${i+1}.jpg" alt="MAZOO 竞赛路演 PPT：${title}" loading="lazy" decoding="async"><span>放大阅读 ↗</span></button><figcaption>竞赛路演 PPT · ${n}</figcaption></figure></article>`).join('')}</div></div></section>
<section class="mz-section mz-social" id="mz-6"><div class="mz-wrap mazoo-container">${heading('07','SOCIAL MEDIA','让品牌持续出现，<br>让内容积累关系。','以小红书为线上渠道，通过节日、热点与角色日常，让 IP 持续进入年轻用户的信息流。')}<div class="mz-social-grid"><article class="mz-social-column"><div class="mz-social-copy"><span class="mz-social-label">ACCOUNT</span><h3>小红书账号运营</h3><p>以账号作为品牌线上内容阵地，持续沉淀角色内容与用户关系。</p></div>${socialPic('2026/s24_1.jpg','MAZOO 小红书账号与内容运营')}</article><article class="mz-social-column"><div class="mz-social-copy"><span class="mz-social-label">FESTIVAL</span><h3>节日内容</h3><p>围绕节日节点，用角色传递祝福与情绪。</p></div>${socialPic('2026/s24_2.jpg','MAZOO 原创主题内容')}</article><article class="mz-social-column"><div class="mz-social-copy"><span class="mz-social-label">TREND &amp; DAILY</span><h3>热点与日常内容</h3><p>将当下话题融入 IP 情境，建立轻松、可分享的表达。</p></div>${socialPic('2026/s24_3.jpg','MAZOO 节日内容')}</article></div></div></section>
<section class="mz-section mz-offline" id="mz-7"><div class="mz-wrap mazoo-container">${heading('08','OFFLINE','从信息流，<br>走进真实的相遇。','通过文创市集与展览，让观众现场看到产品、接触品牌，也让线上内容拥有真实的线下场景。')}<div class="mz-offline-grid">${pic('2026/s24_4.jpg','MAZOO 线下文创市集现场')}${pic('2026/s24_5.jpg','MAZOO 线下活动与交流')}${pic('2026/s24_6.jpg','MAZOO 市集现场记录')}${pic('2026/s24_7.jpg','MAZOO 产品现场陈列')}</div><p class="mz-offline-note">内容带来认识，产品创造接触，线下交流让品牌与用户的关系更具体。</p></div></section>
<section class="mz-section mz-results" id="mz-8"><div class="mz-wrap mazoo-container">${heading('09','RESULT','从文化 IP，<br>到完整的品牌实践。','以内容积累、渠道反馈与项目荣誉，呈现从品牌构建到传播落地的结果。')}<div class="mz-metrics"><div><strong>50<span>+</span></strong><p>原创内容</p></div><div><strong>3000<span>+</span></strong><p>粉丝</p></div><div><strong>600<span>+</span></strong><p>单篇最高点赞</p></div></div><div class="mz-award"><p>全国大学生电子商务创新创意创业挑战赛</p><strong>省级一等奖</strong></div><div class="mz-conclusion"><p class="mz-eyebrow">BRAND → PRODUCT → CONTENT → CHANNEL</p><h3>让传统文化，<br>成为年轻人愿意亲近的品牌。</h3><p>文化研究与受众洞察定义品牌，IP 设计形成识别，文创产品连接日常，主题内容与线上线下渠道共同建立品牌关系，数据反馈为后续迭代提供依据。</p></div></div></section>
<nav class="wrap next-project mz-project-navigation" aria-label="项目切换"><a class="return-home" href="../../index.html#intro">← 返回首页</a><a class="next-project-link" href="../museum/index.html">下一个项目：厦门大学人类博物馆 ↗</a></nav>
</article>`;
 return shell('从传统文化到年轻品牌 · MAZOO',body,base,'work');
};