module.exports=(o,{esc})=>{
 const image=(file,caption,cls='')=>`<button type="button" class="portrait-book-photo ${cls}" data-image="${file}" data-caption="${esc(caption)}" aria-label="查看原图：${esc(caption)}"><img src="${file}" alt="${esc(caption)}" loading="lazy" decoding="async"></button>`;
 const page=(content,n,side)=>`<div class="portrait-book-page portrait-book-${side}">${content}<span class="portrait-book-folio">CHEN YUE / PHOTOGRAPHY <b>${String(n).padStart(2,'0')}</b></span></div>`;
 const sun='assets/portrait-book/sunlight.jpg',street='assets/portrait-book/street.jpg',flowers='assets/portrait-book/flowers.jpg';
 const spreads=[
 [page(`<div class="book-opening-layout"><div class="portrait-book-note book-opening-label"><small>PORTRAITS / 01</small><p>花店与街角</p></div>${image(flowers,'花店里的花','book-opening-flowers')}${image(street,'街角人像 · 自然光','book-opening-portrait')}</div>`,1,'left'),page(`${image(sun,'花店前的人像','book-image-tall')}<p class="portrait-book-caption">光线、表情与环境</p>`,2,'right')],
 [page(`<div class="book-spring-layout book-spring-left"><span class="book-spring-label">02 / 春日光影</span>${image('assets/portrait-book/spring-motion.jpg','春日人像 · 逆光动态','book-spring-main')}${image('assets/portrait-book/spring-willow.jpg','春日人像 · 柳下回望','book-spring-small')}</div>`,3,'left'),page(`<div class="book-spring-layout book-spring-right">${image('assets/portrait-book/spring-light.jpg','春日人像 · 光下侧影','book-spring-main')}${image('assets/portrait-book/spring-details.jpg','春日人像 · 花与衣袖细节组图','book-spring-small')}<span class="book-spring-label">光影 / 姿态 / 细节</span></div>`,4,'right')],
 [page(`<div class="book-meadow-layout book-meadow-left"><span class="book-meadow-label">03 / 草地肖像</span>${image('assets/portrait-book/meadow-flower.jpg','草地人像 · 花与侧影','book-meadow-first')}${image('assets/portrait-book/meadow-seated.jpg','草地人像 · 坐姿','book-meadow-second')}</div>`,5,'left'),page(`<div class="book-meadow-layout book-meadow-right">${image('assets/portrait-book/meadow-fence-01.jpg','草地人像 · 栅栏光影','book-meadow-wide')}${image('assets/portrait-book/meadow-fence-02.jpg','草地人像 · 回望','book-meadow-lower')}${image('assets/portrait-book/meadow-dandelion.jpg','草地细节 · 蒲公英','book-meadow-detail')}</div>`,6,'right')],
 [page(`<div class="book-graduation-layout book-graduation-left"><span class="book-graduation-label">04 / 毕业季约拍</span>${image('assets/portrait-book/graduation-together.jpg','毕业季约拍 · 双人合影','book-graduation-main')}${image('assets/portrait-book/graduation-cap.jpg','毕业季约拍 · 学士帽肖像','book-graduation-cap')}${image('assets/portrait-book/graduation-campus.jpg','毕业季约拍 · 校园合影组图','book-graduation-campus')}</div>`,7,'left'),page(`<div class="book-graduation-layout book-graduation-right">${image('assets/portrait-book/graduation-classroom.jpg','毕业季约拍 · 教室组图','book-graduation-classroom')}${image('assets/portrait-book/graduation-outdoors.jpg','毕业季约拍 · 校园与树影组图','book-graduation-outdoors')}</div>`,8,'right')]

 ];
 return `<div class="portrait-book-section" id="portrait-book"><div class="portrait-book-stage" tabindex="0" role="region" aria-label="人像摄影书，使用左右方向键翻页"><div class="portrait-book">${spreads.map((pages,i)=>`<div class="portrait-book-spread" data-book-spread="${i}"${i?' hidden':''}>${pages.join('')}</div>`).join('')}<div class="portrait-book-spine" aria-hidden="true"></div></div></div><div class="portrait-book-controls"><span class="portrait-book-hint">一本关于光与日常的摄影书 · 点击照片查看原图</span><div><button type="button" data-book-prev aria-label="上一页">←</button><span data-book-position aria-live="off">01 / ${String(spreads.length).padStart(2,'0')}</span><button type="button" data-book-next aria-label="下一页">→</button><button type="button" data-book-pause aria-pressed="false">暂停翻页 Ⅱ</button></div></div></div>`;
};
