const body=document.body,cursor=document.querySelector('.cursor'),menu=document.querySelector('.menu'),panel=document.querySelector('.menu-panel');
window.addEventListener('load',()=>setTimeout(()=>body.classList.add('loaded'),300));
menu.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.setAttribute('aria-expanded',open);panel.setAttribute('aria-hidden',!open);menu.querySelector('span').textContent=open?'−':'＋'});
panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu.querySelector('span').textContent='＋'}));
window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
document.querySelectorAll('.interactive').forEach(el=>{el.addEventListener('pointerenter',()=>cursor.classList.add('show'));el.addEventListener('pointerleave',()=>cursor.classList.remove('show'))});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const rails=[...document.querySelectorAll('.auto-rail')];
rails.forEach(rail=>{let paused=false,drag=false,start=0,origin=0,moved=false;const speed=Number(rail.dataset.speed||.35);
  [...rail.children].forEach(item=>rail.appendChild(item.cloneNode(true)));const loopWidth=()=>rail.scrollWidth/2;
  const tick=()=>{if(!paused&&!drag){rail.scrollLeft+=speed;if(rail.scrollLeft>=loopWidth())rail.scrollLeft-=loopWidth()}requestAnimationFrame(tick)};tick();
  rail.addEventListener('pointerdown',e=>{drag=true;moved=false;start=e.clientX;origin=rail.scrollLeft;rail.setPointerCapture(e.pointerId)});
  rail.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-start;if(Math.abs(dx)>5)moved=true;rail.scrollLeft=origin-dx*1.2});
  rail.addEventListener('pointerup',()=>{drag=false;if(!moved){paused=!paused;rail.classList.toggle('paused',paused);rail.querySelectorAll('figure').forEach(f=>f.classList.toggle('active',paused))}});
  rail.addEventListener('pointercancel',()=>drag=false);rail.addEventListener('mouseenter',()=>paused=true);rail.addEventListener('mouseleave',()=>{if(!rail.classList.contains('paused'))paused=false});
});

document.querySelectorAll('.vertical-loop').forEach(loop=>{let paused=false;[...loop.children].forEach(item=>loop.appendChild(item.cloneNode(true)));const speed=Number(loop.dataset.speed||.4);const tick=()=>{if(!paused){loop.scrollTop+=speed;if(loop.scrollTop>=loop.scrollHeight/2)loop.scrollTop-=loop.scrollHeight/2}requestAnimationFrame(tick)};tick();loop.addEventListener('click',()=>{paused=!paused;loop.classList.toggle('paused',paused)});loop.addEventListener('mouseenter',()=>paused=true);loop.addEventListener('mouseleave',()=>{if(!loop.classList.contains('paused'))paused=false})});

const lightbox=document.querySelector('.lightbox'),lightImg=lightbox.querySelector('img'),images=[...document.querySelectorAll('main figure img:not(.hue-layer)')];
images.forEach((img,i)=>img.addEventListener('dblclick',()=>{lightImg.src=img.src;lightImg.alt=img.alt;lightbox.querySelector('.lightbox-count').textContent=String(i+1).padStart(2,'0')+' / '+images.length;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');body.style.overflow='hidden'}));
const close=()=>{lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');body.style.overflow=''};lightbox.querySelector('button').addEventListener('click',close);lightbox.addEventListener('click',e=>{if(e.target===lightbox)close()});window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});

const sphereStage=document.querySelector('.sphere-stage'),sphere=document.querySelector('.sphere');
if(sphereStage&&sphere){const cards=[...sphere.querySelectorAll('.sphere-card')],radius=innerWidth<760?185:305;cards.forEach((card,i)=>{const lon=i*(360/cards.length),lat=i%2===0?-13:13;card.style.transform=`rotateY(${lon}deg) rotateX(${lat}deg) translateZ(${radius}px)`;card.addEventListener('click',()=>{if(sphereStage.dataset.dragged==='true')return;const img=card.querySelector('img');lightImg.src=img.src;lightImg.alt=img.alt;lightbox.querySelector('.lightbox-count').textContent=card.dataset.label||'POSTER';lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');body.style.overflow='hidden'})});let tx=-7,ty=0,cx=-7,cy=0,fx=0,fy=0,drag=false,sx=0,sy=0,ox=0,oy=0;sphereStage.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;ox=ty;oy=tx;sphereStage.dataset.dragged='false';sphereStage.setPointerCapture(e.pointerId)});sphereStage.addEventListener('pointermove',e=>{const r=sphereStage.getBoundingClientRect();if(drag){const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>7)sphereStage.dataset.dragged='true';ty=ox+dx*.28;tx=Math.max(-55,Math.min(55,oy-dy*.2))}else{fy=((e.clientX-r.left)/r.width-.5)*8;fx=-((e.clientY-r.top)/r.height-.5)*5}});sphereStage.addEventListener('pointerup',()=>drag=false);sphereStage.addEventListener('pointercancel',()=>drag=false);sphereStage.addEventListener('pointerleave',()=>{if(!drag){fx=0;fy=0}});sphereStage.addEventListener('wheel',e=>{e.preventDefault();ty+=e.deltaY*.08},{passive:false});const animate=()=>{if(!drag)ty+=.025;cx+=(tx+fx-cx)*.075;cy+=(ty+fy-cy)*.075;sphere.style.transform=`rotateX(${cx}deg) rotateY(${cy}deg)`;requestAnimationFrame(animate)};animate()}

const fanSection=document.querySelector('.fan-section'),fanPreview=document.querySelector('.fan-preview');
if(fanSection&&fanPreview){new IntersectionObserver(entries=>entries.forEach(e=>fanSection.classList.toggle('fan-open',e.isIntersecting)),{threshold:.3}).observe(fanSection);const previewImg=fanPreview.querySelector('img'),previewText=fanPreview.querySelector('p');fanSection.querySelectorAll('.fan-card').forEach(card=>card.addEventListener('click',()=>{const img=card.querySelector('img');previewImg.src=img.src;previewImg.alt=img.alt;previewText.textContent=card.querySelector('figcaption')?.textContent||'';fanSection.classList.add('has-selection');fanPreview.classList.add('open');fanPreview.setAttribute('aria-hidden','false')}));const closeFan=()=>{fanPreview.classList.remove('open');fanPreview.setAttribute('aria-hidden','true');fanSection.classList.remove('has-selection')};fanPreview.querySelector('button').addEventListener('click',closeFan);window.addEventListener('keydown',e=>{if(e.key==='Escape')closeFan()})}

const installation=document.querySelector('.installation-experience');
if(installation){const device=installation.querySelector('.sway-device'),panel=installation.querySelector('.feature-panel'),features={cuo:{title:'厝 · 闽南建筑轮廓',text:'上层以瓷片组合出闽南古厝的抽象轮廓，提取燕尾脊等地域建筑符号，将“厝”的文化记忆转化为可被远距离识别的空间形象。'},ci:{title:'瓷 · 德化非遗工艺',text:'装置通体以瓷片打造，以蓝色和青绿色釉色为主。瓷片上的山海纹增强透光性与细节质感，使传统德化瓷艺在机场光环境中获得新的表达。'},chao:{title:'潮 · 海洋动态',text:'下层以蓝调渐变瓷片叠合出潮起潮落的流动肌理，并通过动态构件产生波浪式微动，让“潮”的意象从静态造型变成可感知的空间节奏。'},ting:{title:'听 · 潮汐声场',text:'装置增设柔和白噪音系统模拟潮汐声，形成视觉与听觉联动。旅客靠近时不仅“看见海”，也能“听见潮”，获得更沉浸的候机体验。'}};new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)installation.classList.add('arrived')}),{threshold:.28}).observe(installation);let pointer=0,current=0;installation.addEventListener('pointermove',e=>{const r=installation.getBoundingClientRect();pointer=((e.clientX-r.left)/r.width-.5)*7});installation.addEventListener('pointerleave',()=>pointer=0);const sway=()=>{current+=(pointer-current)*.045;const natural=Math.sin(performance.now()/1250)*.65;device.style.transform=`rotate(${current+natural}deg)`;requestAnimationFrame(sway)};sway();installation.querySelectorAll('.hotspot').forEach(btn=>btn.addEventListener('click',()=>{const item=features[btn.dataset.key];installation.querySelectorAll('.hotspot').forEach(b=>b.classList.toggle('active',b===btn));panel.querySelector('small').textContent='FEATURE · '+btn.querySelector('span').textContent;panel.querySelector('h4').textContent=item.title;panel.querySelector('p').textContent=item.text;panel.classList.add('visible');panel.classList.remove('changing');void panel.offsetWidth;panel.classList.add('changing');if(innerWidth>760)requestAnimationFrame(()=>{const area=installation.getBoundingClientRect(),point=btn.getBoundingClientRect(),height=panel.offsetHeight,desired=point.top-area.top+point.height/2-height/2;panel.style.top=Math.max(24,Math.min(installation.clientHeight-height-24,desired))+'px'})}))}

const rabbitFlip=document.querySelector('.rabbit-flip');
if(rabbitFlip){const pages=[...rabbitFlip.querySelectorAll('.flip-page')],count=rabbitFlip.querySelector('.flip-count span');let index=0,timer;const show=next=>{const old=pages[index];index=(next+pages.length)%pages.length;old.classList.remove('active');old.classList.add('leaving');pages[index].classList.add('active');count.textContent=String(index+1).padStart(2,'0');setTimeout(()=>old.classList.remove('leaving'),900)};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(index+1),4200)};rabbitFlip.addEventListener('click',()=>{show(index+1);restart()});rabbitFlip.addEventListener('keydown',e=>{if(['Enter',' ','ArrowRight'].includes(e.key)){e.preventDefault();show(index+1);restart()}if(e.key==='ArrowLeft'){e.preventDefault();show(index-1);restart()}});restart()}

window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight,ratio=max?scrollY/max:0;document.querySelector('.progress i').style.height=ratio*100+'%';const current=[...document.querySelectorAll('.section-mark')].findLast(s=>s.getBoundingClientRect().top<innerHeight*.5);document.querySelector('.progress span').textContent=current?.dataset.no||''}, {passive:true});
